//
// ModelError.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class ModelError: Codable {

    /** Severity of the error. Low, Medium, High, Fatal etc. */
    public var severity: String?
    /** Succinct message describing the error. */
    public var message: String?


    
    public init(severity: String?, message: String?) {
        self.severity = severity
        self.message = message
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(severity, forKey: "severity")
        try container.encodeIfPresent(message, forKey: "message")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        severity = try container.decodeIfPresent(String.self, forKey: "severity")
        message = try container.decodeIfPresent(String.self, forKey: "message")
    }
}

