//
// Pet.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class Pet: Codable {

    public enum ModelType: String, Codable { 
        case cat = "Cat"
        case dog = "Dog"
        case fish = "Fish"
    }
    /** Name of pet */
    public var name: String
    /** Type of pet */
    public var type: ModelType


    
    public init(name: String, type: ModelType) {
        self.name = name
        self.type = type
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(name, forKey: "name")
        try container.encode(type, forKey: "type")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        name = try container.decode(String.self, forKey: "name")
        type = try container.decode(ModelType.self, forKey: "type")
    }
}

