source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

target 'PeoplePetProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 4.5'

  # Pods for PeoplePetProject

  target 'PeoplePetProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PeoplePetProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
